version: "3.8"

services:
  miminions_app: # This is the name of your service
    build: 
      context: .
    container_name: miminions_container  # This assigns a name to the container
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"  # default: 80:5010
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=${CONTAINER_PORT}
    restart: always
